### ISSUE TITLE
Discord bot online but no answer

### ISSUE THREAD

**Issue by jaceee** [StaticFX/DiscordBotBungee#4]
In version 1.1.X bot answered and inquires arrived, I could only decline, accept would fail, but in version 1.2.X the bot is online but wont answer !help nor !verify. There are no logs at all, as if it wasn't listening.

I could try looking at it but I don't know how to compile this, sorry.

**Comment by StaticFX** [comment]
So since your upgrading from an older version i would recommend you first, to backup all your config files. They have changed a bit in the newer version. Then the next step is to check if your database still has the row called "rank" you need to delete this role. Then just do a clean installation of the bot as descripted here: https://github.com/StaticFX/DiscordBotBungee/wiki/How-to-get-started

**Comment by jaceee** [comment]
I started with 1.2.X, I just rolled back to 1.1.X to try something out, I completely deleted the db and config files and started it fresh again in 1.2.2 after you fixed the SQL bug I reported.
I will try it again, tho, and update this issue if I find anything different.

**Comment by StaticFX** [comment]
Okay good luck. Be sure to hold on to the manual: https://github.com/StaticFX/DiscordBotBungee/wiki/How-to-get-started so everything should work first try
